server:
  port: 8088
management:
#  port: 54001
  # close security. 关闭身份验证，否则无法查询出数据
#  security:
#    enabled: false
  server:
    port: 54001
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env