eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:  
    name: service-hi
  cloud:
    config:
      uri:  http://localhost:8080
endpoints:
  web:
    exposure:
      include: refresh,health,info,env